"""
Seed de datos sintéticos URAB-AI — LSL2026
N=20 radicados de demostración calibrados al diagnóstico del RFP
(subconjunto del corpus sintético N=20.417 para el MVP)
"""
from datetime import datetime, timedelta
import random

SEED_PETICIONES = [
    {
        "radicado": "DP-2026-004821",
        "ciudadano": "María García López",
        "cedula": "52847193",
        "canal": "Web",
        "fecha_radicado": datetime(2026, 6, 14, 8, 42),
        "urgencia": "critica",
        "categoria": "VBG",
        "confianza_ia": 94.0,
        "estado": "Pendiente HITL",
        "profesional_id": "P01",
        "profesional_nombre": "Ana Torres",
        "texto_relato": "Mi pareja me ha amenazado de muerte en varias ocasiones. Tenemos dos hijos menores en el hogar. Necesito protección urgente.",
        "entidades": ["Comisaría de Familia", "ICBF"],
        "etario": "adulto",
        "grupos_especiales": ["vbg", "nna"],
        "requiere_hitl": True,
        "hitl_razon": "Regla hard-coded: NNA detectado + amenaza vital | Doble revisión requerida",
        "hitl_resuelto": False,
        "es_duplicado": False,
        "tiempo_triage_h": 0.02,
        "radicada_por_funcionario": False,
        "contacto_tipo": "celular",
        "contacto_valor": "3001234567",
        "fecha_vencimiento": datetime(2026, 7, 5),
        "explicacion_ia": "El relato describe amenazas de muerte reiteradas con menores de edad en el hogar. La presencia de NNA activa prioridad máxima automáticamente, independiente del clasificador."
    },
    {
        "radicado": "DP-2026-004820",
        "ciudadano": "Carlos Pérez Martínez",
        "cedula": "80123456",
        "canal": "Correo",
        "fecha_radicado": datetime(2026, 6, 14, 7, 15),
        "urgencia": "media",
        "categoria": "Salud",
        "confianza_ia": 88.0,
        "estado": "En gestión",
        "profesional_id": "P02",
        "profesional_nombre": "Luis Morales",
        "texto_relato": "La EPS Sanitas me negó la cirugía de rodilla autorizada por mi médico tratante hace tres meses. He radicado dos reclamaciones sin respuesta.",
        "entidades": ["EPS Sanitas"],
        "etario": "adulto",
        "grupos_especiales": [],
        "requiere_hitl": False,
        "hitl_razon": None,
        "hitl_resuelto": True,
        "es_duplicado": False,
        "tiempo_triage_h": 0.03,
        "radicada_por_funcionario": False,
        "contacto_tipo": "correo",
        "contacto_valor": "carlos.perez@email.com",
        "fecha_vencimiento": datetime(2026, 6, 17),
        "explicacion_ia": "Petición sobre negación de servicios de salud. Sin indicadores de riesgo vital inmediato."
    },
    {
        "radicado": "DP-2026-004819",
        "ciudadano": "Rosa Martínez Cifuentes",
        "cedula": "41987654",
        "canal": "Presencial",
        "fecha_radicado": datetime(2026, 6, 13, 16, 30),
        "urgencia": "alta",
        "categoria": "Desaparición",
        "confianza_ia": 91.0,
        "estado": "Pendiente HITL",
        "profesional_id": "P03",
        "profesional_nombre": "Clara Ruiz",
        "texto_relato": "Mi hijo de 28 años desapareció hace 72 horas. Salió de casa el martes y no volvió. No responde el celular. Ya puse la denuncia en la Fiscalía pero necesito ayuda de la Defensoría.",
        "entidades": ["Fiscalía General de la Nación", "Policía Nacional"],
        "etario": "adulto",
        "etnia": "afro",
        "victima_conflicto": "desplazamiento",
        "grupos_especiales": ["desplazado"],
        "requiere_hitl": True,
        "hitl_razon": "Urgencia alta: desaparición de familiar | HITL obligatorio por categoría",
        "hitl_resuelto": False,
        "es_duplicado": False,
        "tiempo_triage_h": 0.02,
        "radicada_por_funcionario": False,
        "contacto_tipo": "celular",
        "contacto_valor": "3109876543",
        "fecha_vencimiento": datetime(2026, 6, 15),
        "explicacion_ia": "Ciudadana reporta desaparición de familiar hace 72 horas. Hash cadena custodia registrado en M1."
    },
    {
        "radicado": "DP-2026-004818",
        "ciudadano": "Carlos Pérez Martínez",
        "cedula": "80123456",
        "canal": "Web",
        "fecha_radicado": datetime(2026, 6, 13, 9, 0),
        "urgencia": "media",
        "categoria": "Salud",
        "confianza_ia": 82.0,
        "estado": "Pendiente acumulación",
        "profesional_id": "P02",
        "profesional_nombre": "Luis Morales",
        "texto_relato": "Sigo sin respuesta de la EPS sobre mi cirugía. Necesito que me ayuden a resolver este problema con Sanitas.",
        "entidades": ["EPS Sanitas"],
        "etario": "adulto",
        "grupos_especiales": [],
        "requiere_hitl": True,
        "hitl_razon": "M4: posible duplicado de DP-2026-004820 (similitud 89%) — funcionario debe aprobar acumulación",
        "hitl_resuelto": False,
        "es_duplicado": True,
        "duplicado_de": "DP-2026-004820",
        "similitud_pct": 89.0,
        "tiempo_triage_h": 0.03,
        "radicada_por_funcionario": False,
        "contacto_tipo": "correo",
        "contacto_valor": "carlos.perez@email.com",
        "fecha_vencimiento": datetime(2026, 6, 18),
        "explicacion_ia": "Duplicado detectado por M4 — similitud 89% con DP-2026-004820. Mismo ciudadano, misma pretensión."
    },
    {
        "radicado": "DP-2026-004815",
        "ciudadano": "Jhon Ramírez Torres",
        "cedula": "79443210",
        "canal": "Terreno",
        "fecha_radicado": datetime(2026, 5, 13, 10, 0),
        "urgencia": "alta",
        "categoria": "Carcelario",
        "confianza_ia": 87.0,
        "estado": "En gestión",
        "profesional_id": "P05",
        "profesional_nombre": "María Ospina",
        "texto_relato": "Privado de libertad en la Cárcel La Picota. Reporta condiciones inhumanas, falta de agua potable y hacinamiento crítico. No ha recibido visita médica en 4 meses.",
        "entidades": ["INPEC"],
        "etario": "adulto",
        "grupos_especiales": ["privado_libertad"],
        "requiere_hitl": False,
        "hitl_razon": None,
        "hitl_resuelto": True,
        "es_duplicado": False,
        "tiempo_triage_h": 0.05,
        "radicada_por_funcionario": True,
        "funcionario_radicador": "María Ospina (P05)",
        "canal_origen_funcionario": "Recolectada en terreno",
        "contacto_tipo": "correo",
        "contacto_valor": "defensor_familia@email.com",
        "fecha_vencimiento": datetime(2026, 6, 14),
        "explicacion_ia": "Privado de libertad reporta condiciones inhumanas. Caso recolectado en terreno por funcionaria. Término vence hoy."
    },
]

SEED_PROFESIONALES = [
    {"id":"P01","nombre":"Ana Torres","color":"#7C3AED","especialidades":["VBG","NNA"],"casos_activos":847,"hitl_pendientes":2,"terminos_riesgo":0},
    {"id":"P02","nombre":"Luis Morales","color":"#059669","especialidades":["Salud","General"],"casos_activos":1103,"hitl_pendientes":1,"terminos_riesgo":1},
    {"id":"P03","nombre":"Clara Ruiz","color":"#1A3D6B","especialidades":["Desaparición","Conflicto"],"casos_activos":612,"hitl_pendientes":1,"terminos_riesgo":1},
    {"id":"P04","nombre":"Jorge Vargas","color":"#D97706","especialidades":["General"],"casos_activos":954,"hitl_pendientes":0,"terminos_riesgo":0},
    {"id":"P05","nombre":"María Ospina","color":"#DC2626","especialidades":["Carcelario","Conflicto"],"casos_activos":1089,"hitl_pendientes":0,"terminos_riesgo":1},
]

SEED_EVENTOS = [
    # DP-2026-004821
    {"radicado":"DP-2026-004821","titulo":"Radicación recibida","actor":"c","actor_label":"Ciudadana","descripcion":"Petición radicada en canal web con caracterización diferencial completa."},
    {"radicado":"DP-2026-004821","titulo":"Triage automático M2","actor":"ia","actor_label":"Sistema IA","descripcion":"Urgencia CRÍTICA · VBG · confianza 94% · HITL activado por regla hard-coded NNA."},
    {"radicado":"DP-2026-004821","titulo":"Asignación M3","actor":"ia","actor_label":"Sistema IA","descripcion":"Asignada a Ana Torres (P01) por perfil VBG + NNA · carga 847 casos."},
    # DP-2026-004820
    {"radicado":"DP-2026-004820","titulo":"Radicación recibida","actor":"c","actor_label":"Ciudadano","descripcion":"Petición radicada por correo electrónico."},
    {"radicado":"DP-2026-004820","titulo":"Triage automático M2","actor":"ia","actor_label":"Sistema IA","descripcion":"Urgencia MEDIA · Salud · confianza 88% · sin HITL requerido."},
    {"radicado":"DP-2026-004820","titulo":"Asignación M3","actor":"ia","actor_label":"Sistema IA","descripcion":"Asignada a Luis Morales (P02) por perfil Salud."},
    # DP-2026-004819
    {"radicado":"DP-2026-004819","titulo":"Radicación presencial","actor":"c","actor_label":"Ciudadana","descripcion":"Radicación presencial · hash cadena custodia SHA-256:a3f8b2c1..."},
    {"radicado":"DP-2026-004819","titulo":"Triage automático M2","actor":"ia","actor_label":"Sistema IA","descripcion":"Urgencia ALTA · Desaparición · HITL obligatorio por categoría."},
    {"radicado":"DP-2026-004819","titulo":"Asignación M3","actor":"ia","actor_label":"Sistema IA","descripcion":"Asignada a Clara Ruiz (P03) por perfil Desaparición."},
    # DP-2026-004815
    {"radicado":"DP-2026-004815","titulo":"Radicación en terreno","actor":"f","actor_label":"María Ospina","descripcion":"Radicada directamente por funcionaria en visita a La Picota · campos completados manualmente."},
    {"radicado":"DP-2026-004815","titulo":"Triage automático M2","actor":"ia","actor_label":"Sistema IA","descripcion":"Urgencia ALTA · Carcelario · confianza 87%."},
]
